name: Ping Supabase Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Once a day at midnight
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Ping Endpoint
        run: curl -X GET https://sus-forest.vercel.app/api/ping
